name = "day10"
uuid = "5fc93edf-a73d-47e6-ac54-27c46fb74bab"
version = "0.1.0"
authors = ["Richie Jang <richiejang@naver.com>"]

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
Combinatorics = "1.0.3"
DataStructures = "0.19.3"
