name = "day9"
uuid = "9611d24d-1b5d-4319-8d3d-06681b5addbf"
version = "0.1.0"
authors = ["Richie Jang <richiejang@naver.com>"]

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
DataStructures = "0.19.3"
